spring.datasource.url=jdbc:postgresql://localhost:5432/esyrent_db
spring.datasource.username=postgres
spring.datasource.password=Jacklb_192005
spring.datasource.driver-class-name=org.postgresql.Driver

app.cors.allowed-origins=http://localhost:4200